# Generated by Django 4.0.3 on 2022-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('selectedText', models.TextField(help_text='选择文字', max_length=10240, verbose_name='选择文字')),
                ('inputText', models.TextField(help_text='输入文字', max_length=10240, verbose_name='输入文字')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_action',
            },
        ),
    ]
